language: python

python:
    - "2.7"
    - "3.2"
    - "3.3"

install:
    - pip install --use-mirrors -r requirements.txt
    - pip install --use-mirrors nose2
    - git submodule init
    - git submodule update
    - make build

script: PYTHONPATH=tests nose2
