#!bin/python

import sys
import os
from optparse import OptionParser

from mako.template import Template
from mako.lookup import TemplateLookup
from mako.exceptions import text_error_template


def get_meta():
	from tomcrypt import meta
	return meta.__dict__.copy()
	
	
if __name__ == '__main__':


	parser = OptionParser("usage: %prog [FILENAME]")

	opts, args = parser.parse_args(sys.argv[1:])
	if len(args) not in (0, 1):
		parser.error("wrong number of arguments") # Will exit

	if (len(args) == 0) or (args[0] == "-"):
		fo = sys.stdin
	else:
		filename = args[0]
		if not os.path.isfile(filename):
			raise SystemExit("error: can't find %s" % filename)
		fo = open(filename)

	data = fo.read()
	try:
		lookup = TemplateLookup(["."])
		print Template(data, lookup=lookup).render(**get_meta())
	except:
		sys.stderr.write(text_error_template().render())
		exit(1)
