#!/usr/bin/env python

import sys
for line in sys.stdin:
    if line.strip().startswith('# '):
        continue
    elif line.strip().startswith('#'):
        print line.strip()
    else:
        print line.rstrip().replace('##', '')